# Generated by Django 3.2 on 2021-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.PositiveSmallIntegerField(null=True)),
                ('pressure', models.PositiveSmallIntegerField(null=True)),
                ('temperature', models.SmallIntegerField(null=True)),
                ('light', models.PositiveSmallIntegerField(null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
